var loadVosklet=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var n=moduleArg,aa="object"==typeof window,p="undefined"!=typeof WorkerGlobalScope;
if(aa||p){var u=[];let b=(async()=>{try{let h=await caches.open("Vosklet");await h.keys("vosklet-cache-probe",{ignoreSearch:!0});return h}catch{return null}})(),a=[31,139],c=[117,115,116,97,114],d=h=>262<=h.length&&c.every((m,l)=>h[257+l]==m),e=async(h,m)=>{if(d(h))return h;if("undefined"==typeof DecompressionStream){if(1<h.length&&h[0]==a[0]&&h[1]==a[1])throw Error("Model fetch succeeded but gzip decompression is unavailable in this browser (missing DecompressionStream).");throw Error("Fetched model bytes from "+
m+" are invalid: expected a USTAR tar archive or gzip-compressed USTAR tar archive.");}try{let l=(new Blob([h])).stream().pipeThrough(new DecompressionStream("gzip")),w=new Uint8Array(await (new Response(l)).arrayBuffer());if(!d(w))throw Error("decompressed bytes are not a USTAR tar archive");return w}catch(l){throw Error("Unable to decode model as gzip-compressed USTAR tar archive from "+m+": "+(l?.message||l));}},g=URL.createObjectURL(new Blob(["(",(()=>{registerProcessor("VoskletTransferer",class extends AudioWorkletProcessor{constructor(h){super();
this.ea=0;this.ua=h.processorOptions[0];this.ra=new Float32Array(this.ua)}process(h){h[0][0]&&(this.ra.set(h[0][0],this.ea),this.ea+=128,this.ea>=this.ua&&(this.ea=0,this.port.postMessage(this.ra,[this.ra.buffer]),this.ra=new Float32Array(this.ua)));return!0}})}).toString(),")()"],{type:"text/javascript"}));class f extends EventTarget{constructor(){super();u.push(this)}delete(){this.ga.delete()}static async ea(h,m,l,w){let v=new f,r=new Promise((z,F)=>{v.addEventListener("status",A=>{A.detail?F(A.detail):
(w&&(v.findWord=H=>v.ga.findWord(H)),z(v))},{once:!0})}),t=await b,q;if(t){let z=(await t.keys(m,{ignoreSearch:!0}))[0];"undefined"!=typeof z&&z.url.split("?")[1]==l&&(q=await t.match(z))}if(!q){q=await fetch(h,{cache:"no-store"});if(!q.ok)throw"Unable to fetch model, status: "+q.status;q=new Response(await e(new Uint8Array(await q.arrayBuffer()),h));if(t)try{await t.put(m+"?"+l,q.clone())}catch{}}h=await q.arrayBuffer();m=x(h.byteLength);y.set(new Uint8Array(h),m);v.ga=new n.CommonModel(u.length-
1,w,m,h.byteLength);return r}}class k extends EventTarget{constructor(){super();u.push(this)}delete(){this.ga.delete()}static async ea(h,m,l,w,v){let r=new k,t=new Promise((q,z)=>{r.addEventListener("status",F=>{F.detail?z(F.detail):q(r)},{once:!0})});switch(l){case 1:r.ga=new n.Recognizer(u.length-1,m,h);break;case 2:r.ga=new n.Recognizer(u.length-1,m,h,v);break;default:r.ga=new n.Recognizer(u.length-1,m,h,w,0)}return t}}k.prototype.acceptWaveform=function(h){let m=x(4*h.length);ba.set(h,m/4);return this.ga.acceptWaveform(m,
h.length)};k.prototype.finalResult=function(){return this.ga.finalResult()};Object.assign(n,{getModelCache:()=>b,cleanUp:async()=>{for(let h of u)await h.delete();URL.revokeObjectURL(g)},createTransferer:async(h,m)=>{await h.audioWorklet.addModule(g);return new AudioWorkletNode(h,"VoskletTransferer",{channelCountMode:"explicit",numberOfInputs:1,numberOfOutputs:0,channelCount:1,processorOptions:[m]})},createModel:(h,m,l)=>f.ea(h,m,l,!0),createSpkModel:(h,m,l)=>f.ea(h,m,l,!1),createRecognizer:(h,m)=>
k.ea(h.ga,m,1),createRecognizerWithGrm:(h,m,l)=>k.ea(h.ga,m,3,l,null),createRecognizerWithSpkModel:(h,m,l)=>k.ea(h.ga,m,2,null,l.ga)})}p&&(_scriptName=self.location.href);var ca="",da,ea;if(aa||p){try{ca=(new URL(".",_scriptName)).href}catch{}p&&(ea=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});da=async b=>{b=await fetch(b,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var fa=console.log.bind(console),B=console.error.bind(console),ha=!1,ia,ja,ka,la,y,C,D,E,G,ba,ma,na,oa,pa=!1;function qa(){var b=ka.buffer;la=new Int8Array(b);C=new Int16Array(b);y=new Uint8Array(b);D=new Uint16Array(b);E=new Int32Array(b);G=new Uint32Array(b);ba=new Float32Array(b);ma=new Float64Array(b);na=new BigInt64Array(b);oa=new BigUint64Array(b)}var I=0,J=null;
function ra(b){b="Aborted("+b+")";B(b);ha=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ja?.(b);throw b;}var sa;async function ta(b){try{var a=await da(b);return new Uint8Array(a)}catch{}if(ea)b=ea(b);else throw"both async and sync fetching of the wasm failed";return b}async function ua(b,a){try{var c=await ta(b);return await WebAssembly.instantiate(c,a)}catch(d){B(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(b){var a=sa;try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){B(`wasm streaming compile failed: ${d}`),B("falling back to ArrayBuffer instantiation")}return ua(a,b)}class wa{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}var xa=new TextDecoder,ya=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},K=(b,a,c)=>b?xa.decode(y.subarray(b,ya(y,b,a,c))):"";
class za{constructor(b){this.Z=b-24}}var Ba=0,Ca=0,L=b=>{for(var a="";;){var c=y[b++];if(!c)return a;a+=String.fromCharCode(c)}},M={},N={},Da={},O=class extends Error{constructor(b){super(b);this.name="BindingError"}},Ea=b=>{throw new O(b);};
function Fa(b,a,c={}){var d=a.name;if(!b)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(b)){if(c.Ea)return;throw new O(`Cannot register type '${d}' twice`);}N[b]=a;delete Da[b];M.hasOwnProperty(b)&&(a=M[b],delete M[b],a.forEach(e=>e()))}function P(b,a,c={}){return Fa(b,a,c)}
var Ga=(b,a,c)=>{switch(a){case 1:return c?d=>la[d]:d=>y[d];case 2:return c?d=>C[d>>1]:d=>D[d>>1];case 4:return c?d=>E[d>>2]:d=>G[d>>2];case 8:return c?d=>na[d>>3]:d=>oa[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ha=b=>{throw new O(b.X.aa.Y.name+" instance already deleted");},Ia=!1,Ja=()=>{},Q=b=>{if("undefined"===typeof FinalizationRegistry)return Q=a=>a,b;Ia=new FinalizationRegistry(a=>{a=a.X;--a.count.value;0===a.count.value&&(a.ca?a.ha.ka(a.ca):a.aa.Y.ka(a.Z))});
Q=a=>{var c=a.X;c.ca&&Ia.register(a,{X:c},a);return a};Ja=a=>{Ia.unregister(a)};return Q(b)},Ka=[];function La(){}
var Ma=(b,a)=>Object.defineProperty(a,"name",{value:b}),Na={},Oa=(b,a,c)=>{if(void 0===b[a].ba){var d=b[a];b[a]=function(...e){if(!b[a].ba.hasOwnProperty(e.length))throw new O(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].ba})!`);return b[a].ba[e.length].apply(this,e)};b[a].ba=[];b[a].ba[d.na]=d}},Pa=(b,a,c)=>{if(n.hasOwnProperty(b)){if(void 0===c||void 0!==n[b].ba&&void 0!==n[b].ba[c])throw new O(`Cannot register public name '${b}' twice`);Oa(n,
b,b);if(n[b].ba.hasOwnProperty(c))throw new O(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[b].ba[c]=a}else n[b]=a,n[b].na=c},Qa=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Ra(b,a,c,d,e,g,f,k){this.name=b;this.constructor=a;this.ma=c;this.ka=d;this.da=e;this.Ca=g;this.qa=f;this.Aa=k;this.Ha=[]}
var Sa=(b,a,c)=>{for(;a!==c;){if(!a.qa)throw new O(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.qa(b);a=a.da}return b},Ta=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function Ua(b,a){if(null===a){if(this.va)throw new O(`null is not a valid ${this.name}`);return 0}if(!a.X)throw new O(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.X.Z)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);return Sa(a.X.Z,a.X.aa.Y,this.Y)}
function Va(b,a){if(null===a){if(this.va)throw new O(`null is not a valid ${this.name}`);if(this.ta){var c=this.Ia();null!==b&&b.push(this.ka,c);return c}return 0}if(!a||!a.X)throw new O(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.X.Z)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.sa&&a.X.aa.sa)throw new O(`Cannot convert argument of type ${a.X.ha?a.X.ha.name:a.X.aa.name} to parameter type ${this.name}`);c=Sa(a.X.Z,a.X.aa.Y,this.Y);if(this.ta){if(void 0===
a.X.ca)throw new O("Passing raw pointer to smart pointer is illegal");switch(this.Ka){case 0:if(a.X.ha===this)c=a.X.ca;else throw new O(`Cannot convert argument of type ${a.X.ha?a.X.ha.name:a.X.aa.name} to parameter type ${this.name}`);break;case 1:c=a.X.ca;break;case 2:if(a.X.ha===this)c=a.X.ca;else{var d=a.clone();c=this.Ja(c,Wa(()=>d["delete"]()));null!==b&&b.push(this.ka,c)}break;default:throw new O("Unsupporting sharing policy");}}return c}
function Xa(b,a){if(null===a){if(this.va)throw new O(`null is not a valid ${this.name}`);return 0}if(!a.X)throw new O(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.X.Z)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.X.aa.sa)throw new O(`Cannot convert argument of type ${a.X.aa.name} to parameter type ${this.name}`);return Sa(a.X.Z,a.X.aa.Y,this.Y)}function Ya(b){return this.$(G[b>>2])}
var Za=(b,a,c)=>{if(a===c)return b;if(void 0===c.da)return null;b=Za(b,a,c.da);return null===b?null:c.Aa(b)},$a={},ab=(b,a)=>{if(void 0===a)throw new O("ptr should not be undefined");for(;b.da;)a=b.qa(a),b=b.da;return $a[a]},bb=class extends Error{constructor(b){super(b);this.name="InternalError"}},cb=(b,a)=>{if(!a.aa||!a.Z)throw new bb("makeClassHandle requires ptr and ptrType");if(!!a.ha!==!!a.ca)throw new bb("Both smartPtrType and smartPtr must be specified");a.count={value:1};return Q(Object.create(b,
{X:{value:a,writable:!0}}))};function eb(b,a,c,d,e,g,f,k,h,m,l){this.name=b;this.Y=a;this.va=c;this.sa=d;this.ta=e;this.Ga=g;this.Ka=f;this.ya=k;this.Ia=h;this.Ja=m;this.ka=l;e||void 0!==a.da?this.ia=Va:(this.ia=d?Ua:Xa,this.fa=null)}
var fb=(b,a,c)=>{if(!n.hasOwnProperty(b))throw new bb("Replacing nonexistent public symbol");void 0!==n[b].ba&&void 0!==c?n[b].ba[c]=a:(n[b]=a,n[b].na=c)},gb=[],hb,R=(b,a)=>{b=L(b);var c;(c=gb[a])||(gb[a]=c=hb.get(a));if("function"!=typeof c)throw new O(`unknown function pointer with signature ${b}: ${a}`);return c};class ib extends Error{}
var kb=b=>{b=jb(b);var a=L(b);S(b);return a},lb=(b,a)=>{function c(g){e[g]||N[g]||(Da[g]?Da[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};a.forEach(c);throw new ib(`${b}: `+d.map(kb).join([", "]));},T=(b,a,c)=>{function d(k){k=c(k);if(k.length!==b.length)throw new bb("Mismatched type converter count");for(var h=0;h<b.length;++h)P(b[h],k[h])}b.forEach(k=>Da[k]=a);var e=Array(a.length),g=[],f=0;a.forEach((k,h)=>{N.hasOwnProperty(k)?e[h]=N[k]:(g.push(k),M.hasOwnProperty(k)||(M[k]=[]),M[k].push(()=>
{e[h]=N[k];++f;f===g.length&&d(e)}))});0===g.length&&d(e)},mb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c},nb=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function ob(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].fa)return!0;return!1}
function pb(b,a,c,d,e,g){var f=a.length;if(2>f)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==a[1]&&null!==c,h=ob(a);c=!a[0].Fa;var m=a[0],l=a[1];d=[b,Ea,d,e,nb,m.$.bind(m),l?.ia.bind(l)];for(e=2;e<f;++e)m=a[e],d.push(m.ia.bind(m));if(!h)for(e=k?1:2;e<a.length;++e)null!==a[e].fa&&d.push(a[e].fa);h=ob(a);e=a.length-2;l=[];m=["fn"];k&&m.push("thisWired");for(f=0;f<e;++f)l.push(`arg${f}`),m.push(`arg${f}Wired`);l=l.join(",");m=m.join(",");l=
`return function (${l}) {\n`;h&&(l+="var destructors = [];\n");var w=h?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(l+=`var thisWired = toClassParamWire(${w}, this);\n`);for(f=0;f<e;++f){var r=`toArg${f}Wire`;l+=`var arg${f}Wired = ${r}(${w}, arg${f});\n`;v.push(r)}l+=(c||g?"var rv = ":"")+`invoker(${m});\n`;if(h)l+="runDestructors(destructors);\n";else for(f=k?1:2;f<a.length;++f)g=1===f?"thisWired":"arg"+(f-2)+"Wired",
null!==a[f].fa&&(l+=`${g}_dtor(${g});\n`,v.push(`${g}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(v,l+"}\n"))(...d);return Ma(b,a)}
var qb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},rb=[],U=[0,1,,1,null,1,!0,1,!1,1],Wa=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=rb.pop()||U.length;U[a]=b;U[a+1]=1;return a}},sb={name:"emscripten::val",$:b=>{if(!b)throw new O(`Cannot use deleted val. handle = ${b}`);var a=U[b];9<b&&0===--U[b+1]&&(U[b]=void 0,rb.push(b));return a},ia:(b,a)=>Wa(a),ja:Ya,fa:null},tb=(b,a,c)=>{switch(a){case 1:return c?function(d){return this.$(la[d])}:
function(d){return this.$(y[d])};case 2:return c?function(d){return this.$(C[d>>1])}:function(d){return this.$(D[d>>1])};case 4:return c?function(d){return this.$(E[d>>2])}:function(d){return this.$(G[d>>2])};default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},ub=b=>{var a=N[b];if(void 0===a)throw b=`${"enum"} has unknown type ${kb(b)}`,new O(b);return a},vb=(b,a)=>{switch(a){case 4:return function(c){return this.$(ba[c>>2])};case 8:return function(c){return this.$(ma[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);
}},V=(b,a,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<b.length;++g){var f=b.codePointAt(g);if(127>=f){if(c>=d)break;a[c++]=f}else if(2047>=f){if(c+1>=d)break;a[c++]=192|f>>6;a[c++]=128|f&63}else if(65535>=f){if(c+2>=d)break;a[c++]=224|f>>12;a[c++]=128|f>>6&63;a[c++]=128|f&63}else{if(c+3>=d)break;a[c++]=240|f>>18;a[c++]=128|f>>12&63;a[c++]=128|f>>6&63;a[c++]=128|f&63;g++}}a[c]=0;return c-e},W=b=>{for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);127>=d?a++:2047>=d?a+=2:55296<=d&&57343>=
d?(a+=4,++c):a+=3}return a},wb=new TextDecoder("utf-16le"),xb=(b,a,c)=>{b>>=1;return wb.decode(D.subarray(b,ya(D,b,a/2,c)))},yb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)C[a>>1]=b.charCodeAt(e),a+=2;C[a>>1]=0;return a-d},zb=b=>2*b.length,Ab=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var g=G[b+e];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},Bb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var g=
b.codePointAt(e);65535<g&&e++;E[a>>2]=g;a+=4;if(a+4>c)break}E[a>>2]=0;return a-d},Cb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},X={},Db=b=>{if(!ha)try{b()}catch(a){if(!(a instanceof wa||"unwind"==a))throw a;}},Eb=[],Y=[],Fb=[],Gb=()=>b=>crypto.getRandomValues(b),Hb=b=>{(Hb=Gb())(b)};
(()=>{let b=La.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof La&&c instanceof La))return!1;var d=this.X.aa.Y,e=this.X.Z;c.X=c.X;var g=c.X.aa.Y;for(c=c.X.Z;d.da;)e=d.qa(e),d=d.da;for(;g.da;)c=g.qa(c),g=g.da;return d===g&&e===c},clone:function(){this.X.Z||Ha(this);if(this.X.pa)return this.X.count.value+=1,this;var c=Q,d=Object,e=d.create,g=Object.getPrototypeOf(this),f=this.X;c=c(e.call(d,g,{X:{value:{count:f.count,oa:f.oa,pa:f.pa,Z:f.Z,aa:f.aa,ca:f.ca,ha:f.ha}}}));c.X.count.value+=
1;c.X.oa=!1;return c},["delete"](){this.X.Z||Ha(this);if(this.X.oa&&!this.X.pa)throw new O("Object already scheduled for deletion");Ja(this);var c=this.X;--c.count.value;0===c.count.value&&(c.ca?c.ha.ka(c.ca):c.aa.Y.ka(c.Z));this.X.pa||(this.X.ca=void 0,this.X.Z=void 0)},isDeleted:function(){return!this.X.Z},deleteLater:function(){this.X.Z||Ha(this);if(this.X.oa&&!this.X.pa)throw new O("Object already scheduled for deletion");Ka.push(this);this.X.oa=!0;return this}});const a=Symbol.dispose;a&&(b[a]=
b["delete"])})();
Object.assign(eb.prototype,{Da(b){this.ya&&(b=this.ya(b));return b},xa(b){this.ka?.(b)},ja:Ya,$:function(b){function a(){return this.ta?cb(this.Y.ma,{aa:this.Ga,Z:c,ha:this,ca:b}):cb(this.Y.ma,{aa:this,Z:b})}var c=this.Da(b);if(!c)return this.xa(b),null;var d=ab(this.Y,c);if(void 0!==d){if(0===d.X.count.value)return d.X.Z=c,d.X.ca=b,d.clone();d=d.clone();this.xa(b);return d}d=this.Y.Ca(c);d=Na[d];if(!d)return a.call(this);d=this.sa?d.za:d.pointerType;var e=Za(c,this.Y,d.Y);return null===e?a.call(this):
this.ta?cb(d.Y.ma,{aa:d,Z:e,ha:this,ca:b}):cb(d.Y.ma,{aa:d,Z:e})}});
var S,x,jb,Ib,Jb={a:(b,a,c,d)=>ra(`Assertion failed: ${K(b)}, at: `+[a?K(a):"unknown filename",c,d?K(d):"unknown function"]),b:(b,a,c)=>{var d=new za(b);G[d.Z+16>>2]=0;G[d.Z+4>>2]=a;G[d.Z+8>>2]=c;Ba=b;Ca++;throw Ba;},G:()=>ra(""),p:(b,a,c,d,e)=>{a=L(a);d=0n===d;let g=f=>f;if(d){const f=8*c;g=k=>BigInt.asUintN(f,k);e=g(e)}P(b,{name:a,$:g,ia:(f,k)=>{"number"==typeof k&&(k=BigInt(k));return k},ja:Ga(a,c,!d),fa:null})},K:(b,a,c,d)=>{a=L(a);P(b,{name:a,$:function(e){return!!e},ia:function(e,g){return g?
c:d},ja:function(e){return this.$(y[e])},fa:null})},n:(b,a,c,d,e,g,f,k,h,m,l,w,v)=>{l=L(l);g=R(e,g);k&&=R(f,k);m&&=R(h,m);v=R(w,v);var r=Qa(l);Pa(r,function(){lb(`Cannot construct ${l} due to unbound types`,[d])});T([b,a,c],d?[d]:[],t=>{t=t[0];if(d){var q=t.Y;var z=q.ma}else z=La.prototype;t=Ma(l,function(...Aa){if(Object.getPrototypeOf(this)!==F)throw new O(`Use 'new' to construct ${l}`);if(void 0===A.la)throw new O(`${l} has no accessible constructor`);var db=A.la[Aa.length];if(void 0===db)throw new O(`Tried to invoke ctor of ${l} with invalid number of parameters (${Aa.length}) - expected (${Object.keys(A.la).toString()}) parameters instead!`);
return db.apply(this,Aa)});var F=Object.create(z,{constructor:{value:t}});t.prototype=F;var A=new Ra(l,t,F,v,q,g,k,m);if(A.da){var H;(H=A.da).wa??(H.wa=[]);A.da.wa.push(A)}q=new eb(l,A,!0,!1,!1);H=new eb(l+"*",A,!1,!1,!1);z=new eb(l+" const*",A,!1,!0,!1);Na[b]={pointerType:H,za:z};fb(r,t);return[q,H,z]})},h:(b,a,c,d,e,g)=>{var f=mb(a,c);e=R(d,e);T([],[b],k=>{k=k[0];var h=`constructor ${k.name}`;void 0===k.Y.la&&(k.Y.la=[]);if(void 0!==k.Y.la[a-1])throw new O(`Cannot register multiple constructors with identical number of parameters (${a-
1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.Y.la[a-1]=()=>{lb(`Cannot construct ${k.name} due to unbound types`,f)};T([],f,m=>{m.splice(1,0,null);k.Y.la[a-1]=pb(h,m,null,e,g);return[]});return[]})},e:(b,a,c,d,e,g,f,k,h)=>{var m=mb(c,d);a=L(a);a=qb(a);g=R(e,g);T([],[b],l=>{function w(){lb(`Cannot call ${v} due to unbound types`,m)}l=l[0];var v=`${l.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);k&&l.Y.Ha.push(a);
var r=l.Y.ma,t=r[a];void 0===t||void 0===t.ba&&t.className!==l.name&&t.na===c-2?(w.na=c-2,w.className=l.name,r[a]=w):(Oa(r,a,v),r[a].ba[c-2]=w);T([],m,q=>{q=pb(v,q,l,g,f,h);void 0===r[a].ba?(q.na=c-2,r[a]=q):r[a].ba[c-2]=q;return[]});return[]})},I:b=>P(b,sb),H:(b,a,c,d)=>{function e(){}a=L(a);e.values={};P(b,{name:a,constructor:e,$:function(g){return this.constructor.values[g]},ia:(g,f)=>f.value,ja:tb(a,c,d),fa:null});Pa(a,e)},i:(b,a,c)=>{var d=ub(b);a=L(a);b=d.constructor;d=Object.create(d.constructor.prototype,
{value:{value:c},constructor:{value:Ma(`${d.name}_${a}`,function(){})}});b.values[c]=d;b[a]=d},o:(b,a,c)=>{a=L(a);P(b,{name:a,$:d=>d,ia:(d,e)=>e,ja:vb(a,c),fa:null})},P:(b,a,c,d,e,g,f)=>{var k=mb(a,c);b=L(b);b=qb(b);e=R(d,e);Pa(b,function(){lb(`Cannot call ${b} due to unbound types`,k)},a-1);T([],k,h=>{fb(b,pb(b,[h[0],null].concat(h.slice(1)),null,e,g,f),a-1);return[]})},f:(b,a,c,d,e)=>{a=L(a);let g=k=>k;if(0===d){var f=32-8*c;g=k=>k<<f>>>f;e=g(e)}P(b,{name:a,$:g,ia:(k,h)=>h,ja:Ga(a,c,0!==d),fa:null})},
c:(b,a,c)=>{function d(g){return new e(la.buffer,G[g+4>>2],G[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=L(c);P(b,{name:c,$:d,ja:d},{Ea:!0})},J:(b,a)=>{a=L(a);P(b,{name:a,$(c){var d=K(c+4,G[c>>2],!0);S(c);return d},ia(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new O("Cannot pass non-string to std::string");
var g=e?W(d):d.length;var f=x(4+g+1),k=f+4;G[f>>2]=g;e?V(d,y,k,g+1):y.set(d,k);null!==c&&c.push(S,f);return f},ja:Ya,fa(c){S(c)}})},l:(b,a,c)=>{c=L(c);if(2===a){var d=xb;var e=yb;var g=zb}else d=Ab,e=Bb,g=Cb;P(b,{name:c,$:f=>{var k=d(f+4,G[f>>2]*a,!0);S(f);return k},ia:(f,k)=>{if("string"!=typeof k)throw new O(`Cannot pass non-string to C++ string type ${c}`);var h=g(k),m=x(4+h+a);G[m>>2]=h/a;e(k,m+4,h+a);null!==f&&f.push(S,m);return m},ja:Ya,fa(f){S(f)}})},L:(b,a)=>{a=L(a);P(b,{Fa:!0,name:a,$:()=>
{},ia:()=>{}})},r:()=>{},s:(b,a)=>{X[b]&&(clearTimeout(X[b].id),delete X[b]);if(!a)return 0;var c=setTimeout(()=>{delete X[b];Db(()=>Ib(b,performance.now()))},a);X[b]={id:c,Oa:a};return 0},E:(b,a,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[b>>2]=60*Math.max(g,e);E[a>>2]=Number(g!=e);a=f=>{var k=Math.abs(f);return`UTC${0<=f?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};b=a(g);a=a(e);e<
g?(V(b,y,c,17),V(a,y,d,17)):(V(b,y,d,17),V(a,y,c,17))},z:(b,a)=>y.set(Y[b].Ba,a),x:()=>Eb.length,y:()=>Y.length,v:(b,a)=>{b=Eb[b].La;V(b,y,a,W(b)+1)},t:b=>Y[b].mode,A:b=>Y[b].Ba.length,w:(b,a)=>{b=Eb[b].Ma;V(b,y,a,W(b)+1)},u:(b,a)=>{b=Y[b].Na;V(b,y,a,W(b)+1)},C:()=>{a:{if(!Fb.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(b=window.prompt("Input: "),null!==b&&(b+="\n"));if(!b){var a=null;break a}a=Array(W(b)+1);b=V(b,a,0,a.length);a.length=b;Fb=a}a=Fb.shift()}return"number"===
typeof a?a:-1},g:function(b,a){u[b].dispatchEvent(new CustomEvent("status",{detail:0===a?null:K(a)}))},M:b=>{console.error(K(b))},O:b=>{console.log(K(b))},N:b=>{console.warn(K(b))},d:()=>Date.now(),j:b=>B(K(b)),k:()=>performance.now(),B:b=>fa(K(b)),F:b=>{var a=y.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(b,d)/65536))-ka.buffer.byteLength+65535)/65536|0;try{ka.grow(d);qa();var e=1;break a}catch(g){}e=
void 0}if(e)return!0}return!1},m:b=>{throw new wa(b);},q:b=>{throw new wa(b);},D:(b,a)=>{Hb(y.subarray(b,b+a));return 0}},Z=await (async function(){function b(c){Z=c.exports;ka=Z.Q;qa();hb=Z.V;c=Z;S=c.S;x=c.T;jb=c.U;Ib=c.W;I--;0==I&&J&&(c=J,J=null,c());return Z}I++;var a={a:Jb};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(a,(d,e)=>{c(b(d,e))})});sa??=n.locateFile?n.locateFile("Vosklet.single.wasm",ca):ca+"Vosklet.single.wasm";return b((await va(a)).instance)}());
function Kb(){0<I?J=Kb:0<I?J=Kb:(n.calledRun=!0,ha||(pa=!0,Z.R(),ia?.(n)))}Kb();pa?moduleRtn=n:moduleRtn=new Promise((b,a)=>{ia=b;ja=a});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=loadVosklet;module.exports.default=loadVosklet}else if(typeof define==="function"&&define["amd"])define([],()=>loadVosklet);
