var loadVosklet=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var n=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope;
if(aa){var q=[];let b=caches.open("Vosklet"),a=[31,139],c=[117,115,116,97,114],d=k=>262<=k.length&&c.every((m,l)=>k[257+l]==m),e=async(k,m)=>{if(d(k))return k;if("undefined"==typeof DecompressionStream){if(1<k.length&&k[0]==a[0]&&k[1]==a[1])throw Error("Model fetch succeeded but gzip decompression is unavailable in this browser (missing DecompressionStream).");throw Error("Fetched model bytes from "+m+" are invalid: expected a USTAR tar archive or gzip-compressed USTAR tar archive.");}try{let l=(new Blob([k])).stream().pipeThrough(new DecompressionStream("gzip")),
w=new Uint8Array(await (new Response(l)).arrayBuffer());if(!d(w))throw Error("decompressed bytes are not a USTAR tar archive");return w}catch(l){throw Error("Unable to decode model as gzip-compressed USTAR tar archive from "+m+": "+(l?.message||l));}},g=URL.createObjectURL(new Blob(["(",(()=>{registerProcessor("VoskletTransferer",class extends AudioWorkletProcessor{constructor(k){super();this.ea=0;this.ua=k.processorOptions[0];this.ra=new Float32Array(this.ua)}process(k){k[0][0]&&(this.ra.set(k[0][0],
this.ea),this.ea+=128,this.ea>=this.ua&&(this.ea=0,this.port.postMessage(this.ra,[this.ra.buffer]),this.ra=new Float32Array(this.ua)));return!0}})}).toString(),")()"],{type:"text/javascript"}));class f extends EventTarget{constructor(){super();q.push(this)}delete(){this.ia.delete()}static async ea(k,m,l,w){let u=new f,r=new Promise((C,F)=>{u.addEventListener("status",z=>{z.detail?F(z.detail):(w&&(u.findWord=H=>u.ia.findWord(H)),C(u))},{once:!0})}),v=await caches.open("Vosklet");var p=(await v.keys(m,
{ignoreSearch:!0}))[0];if("undefined"==typeof p||p.url.split("?")[1]!=l){p=await fetch(k,{cache:"no-store"});if(!p.ok)throw"Unable to fetch model, status: "+p.status;p=new Response(await e(new Uint8Array(await p.arrayBuffer()),k));await v.put(m+"?"+l,p.clone())}else p=await v.match(p);k=await p.arrayBuffer();m=t(k.byteLength);x.set(new Uint8Array(k),m);u.ia=new n.CommonModel(q.length-1,w,m,k.byteLength);return r}}class h extends EventTarget{constructor(){super();q.push(this)}delete(){this.ia.delete()}static async ea(k,
m,l,w,u){let r=new h,v=new Promise((p,C)=>{r.addEventListener("status",F=>{F.detail?C(F.detail):p(r)},{once:!0})});switch(l){case 1:r.ia=new n.Recognizer(q.length-1,m,k);break;case 2:r.ia=new n.Recognizer(q.length-1,m,k,u);break;default:r.ia=new n.Recognizer(q.length-1,m,k,w,0)}return v}}n={getModelCache:()=>b,cleanUp:async()=>{for(let k of q)await k.delete();URL.revokeObjectURL(g)},createTransferer:async(k,m)=>{await k.audioWorklet.addModule(g);return new AudioWorkletNode(k,"VoskletTransferer",{channelCountMode:"explicit",
numberOfInputs:1,numberOfOutputs:0,channelCount:1,processorOptions:[m]})},createModel:(k,m,l)=>f.ea(k,m,l,!0),createSpkModel:(k,m,l)=>f.ea(k,m,l,!1),createRecognizer:(k,m)=>h.ea(k.ia,m,1),createRecognizerWithGrm:(k,m,l)=>h.ea(k.ia,m,3,l,null),createRecognizerWithSpkModel:(k,m,l)=>h.ea(k.ia,m,2,null,l.ia)}}ba&&(_scriptName=self.location.href);var ca="",da,ea;
if(aa||ba){try{ca=(new URL(".",_scriptName)).href}catch{}ba&&(ea=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});da=async b=>{b=await fetch(b,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var fa=console.log.bind(console),y=console.error.bind(console),ha=!1,ia,ja,A,ka,x,B,D,E,G,la,ma,na,oa,pa=!1;
function qa(){var b=A.buffer;ka=new Int8Array(b);B=new Int16Array(b);x=new Uint8Array(b);D=new Uint16Array(b);E=new Int32Array(b);G=new Uint32Array(b);la=new Float32Array(b);ma=new Float64Array(b);na=new BigInt64Array(b);oa=new BigUint64Array(b)}var I=0,J=null;function ra(b){b="Aborted("+b+")";y(b);ha=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ja?.(b);throw b;}var sa;
async function ta(b){try{var a=await da(b);return new Uint8Array(a)}catch{}if(ea)b=ea(b);else throw"both async and sync fetching of the wasm failed";return b}async function ua(b,a){try{var c=await ta(b);return await WebAssembly.instantiate(c,a)}catch(d){y(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(b){var a=sa;try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){y(`wasm streaming compile failed: ${d}`),y("falling back to ArrayBuffer instantiation")}return ua(a,b)}class wa{name="ExitStatus";constructor(b){this.message=`Program terminated with exit(${b})`;this.status=b}}var xa=new TextDecoder,za=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},K=(b,a,c)=>b?xa.decode(x.subarray(b,za(x,b,a,c))):"";
class Aa{constructor(b){this.Z=b-24}}var Ba=0,Ca=0,L=b=>{for(var a="";;){var c=x[b++];if(!c)return a;a+=String.fromCharCode(c)}},M={},N={},Da={},O=class extends Error{constructor(b){super(b);this.name="BindingError"}},Ea=b=>{throw new O(b);};
function Fa(b,a,c={}){var d=a.name;if(!b)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(b)){if(c.Ea)return;throw new O(`Cannot register type '${d}' twice`);}N[b]=a;delete Da[b];M.hasOwnProperty(b)&&(a=M[b],delete M[b],a.forEach(e=>e()))}function P(b,a,c={}){return Fa(b,a,c)}
var Ga=(b,a,c)=>{switch(a){case 1:return c?d=>ka[d]:d=>x[d];case 2:return c?d=>B[d>>1]:d=>D[d>>1];case 4:return c?d=>E[d>>2]:d=>G[d>>2];case 8:return c?d=>na[d>>3]:d=>oa[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ha=b=>{throw new O(b.X.aa.Y.name+" instance already deleted");},Ia=!1,Ja=()=>{},Q=b=>{if("undefined"===typeof FinalizationRegistry)return Q=a=>a,b;Ia=new FinalizationRegistry(a=>{a=a.X;--a.count.value;0===a.count.value&&(a.ca?a.ga.ka(a.ca):a.aa.Y.ka(a.Z))});
Q=a=>{var c=a.X;c.ca&&Ia.register(a,{X:c},a);return a};Ja=a=>{Ia.unregister(a)};return Q(b)},Ka=[];function La(){}
var Ma=(b,a)=>Object.defineProperty(a,"name",{value:b}),Na={},Oa=(b,a,c)=>{if(void 0===b[a].ba){var d=b[a];b[a]=function(...e){if(!b[a].ba.hasOwnProperty(e.length))throw new O(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].ba})!`);return b[a].ba[e.length].apply(this,e)};b[a].ba=[];b[a].ba[d.na]=d}},Pa=(b,a,c)=>{if(n.hasOwnProperty(b)){if(void 0===c||void 0!==n[b].ba&&void 0!==n[b].ba[c])throw new O(`Cannot register public name '${b}' twice`);Oa(n,
b,b);if(n[b].ba.hasOwnProperty(c))throw new O(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[b].ba[c]=a}else n[b]=a,n[b].na=c},Qa=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Ra(b,a,c,d,e,g,f,h){this.name=b;this.constructor=a;this.ma=c;this.ka=d;this.da=e;this.Ca=g;this.qa=f;this.Aa=h;this.Ha=[]}
var Sa=(b,a,c)=>{for(;a!==c;){if(!a.qa)throw new O(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.qa(b);a=a.da}return b},Ta=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function Ua(b,a){if(null===a){if(this.va)throw new O(`null is not a valid ${this.name}`);return 0}if(!a.X)throw new O(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.X.Z)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);return Sa(a.X.Z,a.X.aa.Y,this.Y)}
function Va(b,a){if(null===a){if(this.va)throw new O(`null is not a valid ${this.name}`);if(this.ta){var c=this.Ia();null!==b&&b.push(this.ka,c);return c}return 0}if(!a||!a.X)throw new O(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.X.Z)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.sa&&a.X.aa.sa)throw new O(`Cannot convert argument of type ${a.X.ga?a.X.ga.name:a.X.aa.name} to parameter type ${this.name}`);c=Sa(a.X.Z,a.X.aa.Y,this.Y);if(this.ta){if(void 0===
a.X.ca)throw new O("Passing raw pointer to smart pointer is illegal");switch(this.Ka){case 0:if(a.X.ga===this)c=a.X.ca;else throw new O(`Cannot convert argument of type ${a.X.ga?a.X.ga.name:a.X.aa.name} to parameter type ${this.name}`);break;case 1:c=a.X.ca;break;case 2:if(a.X.ga===this)c=a.X.ca;else{var d=a.clone();c=this.Ja(c,Wa(()=>d["delete"]()));null!==b&&b.push(this.ka,c)}break;default:throw new O("Unsupporting sharing policy");}}return c}
function Xa(b,a){if(null===a){if(this.va)throw new O(`null is not a valid ${this.name}`);return 0}if(!a.X)throw new O(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.X.Z)throw new O(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.X.aa.sa)throw new O(`Cannot convert argument of type ${a.X.aa.name} to parameter type ${this.name}`);return Sa(a.X.Z,a.X.aa.Y,this.Y)}function Ya(b){return this.$(G[b>>2])}
var Za=(b,a,c)=>{if(a===c)return b;if(void 0===c.da)return null;b=Za(b,a,c.da);return null===b?null:c.Aa(b)},$a={},ab=(b,a)=>{if(void 0===a)throw new O("ptr should not be undefined");for(;b.da;)a=b.qa(a),b=b.da;return $a[a]},bb=class extends Error{constructor(b){super(b);this.name="InternalError"}},cb=(b,a)=>{if(!a.aa||!a.Z)throw new bb("makeClassHandle requires ptr and ptrType");if(!!a.ga!==!!a.ca)throw new bb("Both smartPtrType and smartPtr must be specified");a.count={value:1};return Q(Object.create(b,
{X:{value:a,writable:!0}}))};function eb(b,a,c,d,e,g,f,h,k,m,l){this.name=b;this.Y=a;this.va=c;this.sa=d;this.ta=e;this.Ga=g;this.Ka=f;this.ya=h;this.Ia=k;this.Ja=m;this.ka=l;e||void 0!==a.da?this.ha=Va:(this.ha=d?Ua:Xa,this.fa=null)}
var fb=(b,a,c)=>{if(!n.hasOwnProperty(b))throw new bb("Replacing nonexistent public symbol");void 0!==n[b].ba&&void 0!==c?n[b].ba[c]=a:(n[b]=a,n[b].na=c)},gb=[],hb,R=(b,a)=>{b=L(b);var c;(c=gb[a])||(gb[a]=c=hb.get(a));if("function"!=typeof c)throw new O(`unknown function pointer with signature ${b}: ${a}`);return c};class ib extends Error{}
var kb=b=>{b=jb(b);var a=L(b);S(b);return a},lb=(b,a)=>{function c(g){e[g]||N[g]||(Da[g]?Da[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};a.forEach(c);throw new ib(`${b}: `+d.map(kb).join([", "]));},T=(b,a,c)=>{function d(h){h=c(h);if(h.length!==b.length)throw new bb("Mismatched type converter count");for(var k=0;k<b.length;++k)P(b[k],h[k])}b.forEach(h=>Da[h]=a);var e=Array(a.length),g=[],f=0;a.forEach((h,k)=>{N.hasOwnProperty(h)?e[k]=N[h]:(g.push(h),M.hasOwnProperty(h)||(M[h]=[]),M[h].push(()=>
{e[k]=N[h];++f;f===g.length&&d(e)}))});0===g.length&&d(e)},mb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c},nb=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function ob(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].fa)return!0;return!1}
function pb(b,a,c,d,e,g){var f=a.length;if(2>f)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==a[1]&&null!==c,k=ob(a);c=!a[0].Fa;var m=a[0],l=a[1];d=[b,Ea,d,e,nb,m.$.bind(m),l?.ha.bind(l)];for(e=2;e<f;++e)m=a[e],d.push(m.ha.bind(m));if(!k)for(e=h?1:2;e<a.length;++e)null!==a[e].fa&&d.push(a[e].fa);k=ob(a);e=a.length-2;l=[];m=["fn"];h&&m.push("thisWired");for(f=0;f<e;++f)l.push(`arg${f}`),m.push(`arg${f}Wired`);l=l.join(",");m=m.join(",");l=
`return function (${l}) {\n`;k&&(l+="var destructors = [];\n");var w=k?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(l+=`var thisWired = toClassParamWire(${w}, this);\n`);for(f=0;f<e;++f){var r=`toArg${f}Wire`;l+=`var arg${f}Wired = ${r}(${w}, arg${f});\n`;u.push(r)}l+=(c||g?"var rv = ":"")+`invoker(${m});\n`;if(k)l+="runDestructors(destructors);\n";else for(f=h?1:2;f<a.length;++f)g=1===f?"thisWired":"arg"+(f-2)+"Wired",
null!==a[f].fa&&(l+=`${g}_dtor(${g});\n`,u.push(`${g}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(u,l+"}\n"))(...d);return Ma(b,a)}
var qb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},rb=[],U=[0,1,,1,null,1,!0,1,!1,1],Wa=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=rb.pop()||U.length;U[a]=b;U[a+1]=1;return a}},sb={name:"emscripten::val",$:b=>{if(!b)throw new O(`Cannot use deleted val. handle = ${b}`);var a=U[b];9<b&&0===--U[b+1]&&(U[b]=void 0,rb.push(b));return a},ha:(b,a)=>Wa(a),ja:Ya,fa:null},tb=(b,a,c)=>{switch(a){case 1:return c?function(d){return this.$(ka[d])}:
function(d){return this.$(x[d])};case 2:return c?function(d){return this.$(B[d>>1])}:function(d){return this.$(D[d>>1])};case 4:return c?function(d){return this.$(E[d>>2])}:function(d){return this.$(G[d>>2])};default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},ub=b=>{var a=N[b];if(void 0===a)throw b=`${"enum"} has unknown type ${kb(b)}`,new O(b);return a},vb=(b,a)=>{switch(a){case 4:return function(c){return this.$(la[c>>2])};case 8:return function(c){return this.$(ma[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);
}},V=(b,a,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<b.length;++g){var f=b.codePointAt(g);if(127>=f){if(c>=d)break;a[c++]=f}else if(2047>=f){if(c+1>=d)break;a[c++]=192|f>>6;a[c++]=128|f&63}else if(65535>=f){if(c+2>=d)break;a[c++]=224|f>>12;a[c++]=128|f>>6&63;a[c++]=128|f&63}else{if(c+3>=d)break;a[c++]=240|f>>18;a[c++]=128|f>>12&63;a[c++]=128|f>>6&63;a[c++]=128|f&63;g++}}a[c]=0;return c-e},W=b=>{for(var a=0,c=0;c<b.length;++c){var d=b.charCodeAt(c);127>=d?a++:2047>=d?a+=2:55296<=d&&57343>=
d?(a+=4,++c):a+=3}return a},wb=new TextDecoder("utf-16le"),xb=(b,a,c)=>{b>>=1;return wb.decode(D.subarray(b,za(D,b,a/2,c)))},yb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)B[a>>1]=b.charCodeAt(e),a+=2;B[a>>1]=0;return a-d},zb=b=>2*b.length,Ab=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var g=G[b+e];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},Bb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var g=
b.codePointAt(e);65535<g&&e++;E[a>>2]=g;a+=4;if(a+4>c)break}E[a>>2]=0;return a-d},Cb=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},X={},Db=b=>{if(!ha)try{b()}catch(a){if(!(a instanceof wa||"unwind"==a))throw a;}},Eb=[],Y=[],Fb=[],Gb=()=>b=>crypto.getRandomValues(b),Hb=b=>{(Hb=Gb())(b)};
(()=>{let b=La.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof La&&c instanceof La))return!1;var d=this.X.aa.Y,e=this.X.Z;c.X=c.X;var g=c.X.aa.Y;for(c=c.X.Z;d.da;)e=d.qa(e),d=d.da;for(;g.da;)c=g.qa(c),g=g.da;return d===g&&e===c},clone:function(){this.X.Z||Ha(this);if(this.X.pa)return this.X.count.value+=1,this;var c=Q,d=Object,e=d.create,g=Object.getPrototypeOf(this),f=this.X;c=c(e.call(d,g,{X:{value:{count:f.count,oa:f.oa,pa:f.pa,Z:f.Z,aa:f.aa,ca:f.ca,ga:f.ga}}}));c.X.count.value+=
1;c.X.oa=!1;return c},["delete"](){this.X.Z||Ha(this);if(this.X.oa&&!this.X.pa)throw new O("Object already scheduled for deletion");Ja(this);var c=this.X;--c.count.value;0===c.count.value&&(c.ca?c.ga.ka(c.ca):c.aa.Y.ka(c.Z));this.X.pa||(this.X.ca=void 0,this.X.Z=void 0)},isDeleted:function(){return!this.X.Z},deleteLater:function(){this.X.Z||Ha(this);if(this.X.oa&&!this.X.pa)throw new O("Object already scheduled for deletion");Ka.push(this);this.X.oa=!0;return this}});const a=Symbol.dispose;a&&(b[a]=
b["delete"])})();
Object.assign(eb.prototype,{Da(b){this.ya&&(b=this.ya(b));return b},xa(b){this.ka?.(b)},ja:Ya,$:function(b){function a(){return this.ta?cb(this.Y.ma,{aa:this.Ga,Z:c,ga:this,ca:b}):cb(this.Y.ma,{aa:this,Z:b})}var c=this.Da(b);if(!c)return this.xa(b),null;var d=ab(this.Y,c);if(void 0!==d){if(0===d.X.count.value)return d.X.Z=c,d.X.ca=b,d.clone();d=d.clone();this.xa(b);return d}d=this.Y.Ca(c);d=Na[d];if(!d)return a.call(this);d=this.sa?d.za:d.pointerType;var e=Za(c,this.Y,d.Y);return null===e?a.call(this):
this.ta?cb(d.Y.ma,{aa:d,Z:e,ga:this,ca:b}):cb(d.Y.ma,{aa:d,Z:e})}});
var S,t,jb,Ib,Jb={a:(b,a,c,d)=>ra(`Assertion failed: ${K(b)}, at: `+[a?K(a):"unknown filename",c,d?K(d):"unknown function"]),b:(b,a,c)=>{var d=new Aa(b);G[d.Z+16>>2]=0;G[d.Z+4>>2]=a;G[d.Z+8>>2]=c;Ba=b;Ca++;throw Ba;},G:()=>ra(""),p:(b,a,c,d,e)=>{a=L(a);d=0n===d;let g=f=>f;if(d){const f=8*c;g=h=>BigInt.asUintN(f,h);e=g(e)}P(b,{name:a,$:g,ha:(f,h)=>{"number"==typeof h&&(h=BigInt(h));return h},ja:Ga(a,c,!d),fa:null})},K:(b,a,c,d)=>{a=L(a);P(b,{name:a,$:function(e){return!!e},ha:function(e,g){return g?
c:d},ja:function(e){return this.$(x[e])},fa:null})},n:(b,a,c,d,e,g,f,h,k,m,l,w,u)=>{l=L(l);g=R(e,g);h&&=R(f,h);m&&=R(k,m);u=R(w,u);var r=Qa(l);Pa(r,function(){lb(`Cannot construct ${l} due to unbound types`,[d])});T([b,a,c],d?[d]:[],v=>{v=v[0];if(d){var p=v.Y;var C=p.ma}else C=La.prototype;v=Ma(l,function(...ya){if(Object.getPrototypeOf(this)!==F)throw new O(`Use 'new' to construct ${l}`);if(void 0===z.la)throw new O(`${l} has no accessible constructor`);var db=z.la[ya.length];if(void 0===db)throw new O(`Tried to invoke ctor of ${l} with invalid number of parameters (${ya.length}) - expected (${Object.keys(z.la).toString()}) parameters instead!`);
return db.apply(this,ya)});var F=Object.create(C,{constructor:{value:v}});v.prototype=F;var z=new Ra(l,v,F,u,p,g,h,m);if(z.da){var H;(H=z.da).wa??(H.wa=[]);z.da.wa.push(z)}p=new eb(l,z,!0,!1,!1);H=new eb(l+"*",z,!1,!1,!1);C=new eb(l+" const*",z,!1,!0,!1);Na[b]={pointerType:H,za:C};fb(r,v);return[p,H,C]})},h:(b,a,c,d,e,g)=>{var f=mb(a,c);e=R(d,e);T([],[b],h=>{h=h[0];var k=`constructor ${h.name}`;void 0===h.Y.la&&(h.Y.la=[]);if(void 0!==h.Y.la[a-1])throw new O(`Cannot register multiple constructors with identical number of parameters (${a-
1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.Y.la[a-1]=()=>{lb(`Cannot construct ${h.name} due to unbound types`,f)};T([],f,m=>{m.splice(1,0,null);h.Y.la[a-1]=pb(k,m,null,e,g);return[]});return[]})},e:(b,a,c,d,e,g,f,h,k)=>{var m=mb(c,d);a=L(a);a=qb(a);g=R(e,g);T([],[b],l=>{function w(){lb(`Cannot call ${u} due to unbound types`,m)}l=l[0];var u=`${l.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);h&&l.Y.Ha.push(a);
var r=l.Y.ma,v=r[a];void 0===v||void 0===v.ba&&v.className!==l.name&&v.na===c-2?(w.na=c-2,w.className=l.name,r[a]=w):(Oa(r,a,u),r[a].ba[c-2]=w);T([],m,p=>{p=pb(u,p,l,g,f,k);void 0===r[a].ba?(p.na=c-2,r[a]=p):r[a].ba[c-2]=p;return[]});return[]})},I:b=>P(b,sb),H:(b,a,c,d)=>{function e(){}a=L(a);e.values={};P(b,{name:a,constructor:e,$:function(g){return this.constructor.values[g]},ha:(g,f)=>f.value,ja:tb(a,c,d),fa:null});Pa(a,e)},i:(b,a,c)=>{var d=ub(b);a=L(a);b=d.constructor;d=Object.create(d.constructor.prototype,
{value:{value:c},constructor:{value:Ma(`${d.name}_${a}`,function(){})}});b.values[c]=d;b[a]=d},o:(b,a,c)=>{a=L(a);P(b,{name:a,$:d=>d,ha:(d,e)=>e,ja:vb(a,c),fa:null})},P:(b,a,c,d,e,g,f)=>{var h=mb(a,c);b=L(b);b=qb(b);e=R(d,e);Pa(b,function(){lb(`Cannot call ${b} due to unbound types`,h)},a-1);T([],h,k=>{fb(b,pb(b,[k[0],null].concat(k.slice(1)),null,e,g,f),a-1);return[]})},f:(b,a,c,d,e)=>{a=L(a);let g=h=>h;if(0===d){var f=32-8*c;g=h=>h<<f>>>f;e=g(e)}P(b,{name:a,$:g,ha:(h,k)=>k,ja:Ga(a,c,0!==d),fa:null})},
c:(b,a,c)=>{function d(g){return new e(ka.buffer,G[g+4>>2],G[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=L(c);P(b,{name:c,$:d,ja:d},{Ea:!0})},J:(b,a)=>{a=L(a);P(b,{name:a,$(c){var d=K(c+4,G[c>>2],!0);S(c);return d},ha(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new O("Cannot pass non-string to std::string");
var g=e?W(d):d.length;var f=t(4+g+1),h=f+4;G[f>>2]=g;e?V(d,x,h,g+1):x.set(d,h);null!==c&&c.push(S,f);return f},ja:Ya,fa(c){S(c)}})},l:(b,a,c)=>{c=L(c);if(2===a){var d=xb;var e=yb;var g=zb}else d=Ab,e=Bb,g=Cb;P(b,{name:c,$:f=>{var h=d(f+4,G[f>>2]*a,!0);S(f);return h},ha:(f,h)=>{if("string"!=typeof h)throw new O(`Cannot pass non-string to C++ string type ${c}`);var k=g(h),m=t(4+k+a);G[m>>2]=k/a;e(h,m+4,k+a);null!==f&&f.push(S,m);return m},ja:Ya,fa(f){S(f)}})},L:(b,a)=>{a=L(a);P(b,{Fa:!0,name:a,$:()=>
{},ha:()=>{}})},r:()=>{},s:(b,a)=>{X[b]&&(clearTimeout(X[b].id),delete X[b]);if(!a)return 0;var c=setTimeout(()=>{delete X[b];Db(()=>Ib(b,performance.now()))},a);X[b]={id:c,Oa:a};return 0},E:(b,a,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[b>>2]=60*Math.max(g,e);E[a>>2]=Number(g!=e);a=f=>{var h=Math.abs(f);return`UTC${0<=f?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};b=a(g);a=a(e);e<
g?(V(b,x,c,17),V(a,x,d,17)):(V(b,x,d,17),V(a,x,c,17))},z:(b,a)=>x.set(Y[b].Ba,a),x:()=>Eb.length,y:()=>Y.length,v:(b,a)=>{b=Eb[b].La;V(b,x,a,W(b)+1)},t:b=>Y[b].mode,A:b=>Y[b].Ba.length,w:(b,a)=>{b=Eb[b].Ma;V(b,x,a,W(b)+1)},u:(b,a)=>{b=Y[b].Na;V(b,x,a,W(b)+1)},C:()=>{a:{if(!Fb.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(b=window.prompt("Input: "),null!==b&&(b+="\n"));if(!b){var a=null;break a}a=Array(W(b)+1);b=V(b,a,0,a.length);a.length=b;Fb=a}a=Fb.shift()}return"number"===
typeof a?a:-1},g:function(b,a){q[b].dispatchEvent(new CustomEvent("status",{detail:0===a?null:K(a)}))},M:b=>{console.error(K(b))},O:b=>{console.log(K(b))},N:b=>{console.warn(K(b))},d:()=>Date.now(),j:b=>y(K(b)),k:()=>performance.now(),B:b=>fa(K(b)),F:b=>{var a=x.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var d=a*(1+.2/c);d=Math.min(d,b+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(b,d)/65536))-A.buffer.byteLength+65535)/65536|0;try{A.grow(d);qa();var e=1;break a}catch(g){}e=
void 0}if(e)return!0}return!1},m:b=>{throw new wa(b);},q:b=>{throw new wa(b);},D:(b,a)=>{Hb(x.subarray(b,b+a));return 0}},Z=await (async function(){function b(c){Z=c.exports;A=Z.Q;qa();hb=Z.V;c=Z;S=c.S;t=c.T;jb=c.U;Ib=c.W;I--;0==I&&J&&(c=J,J=null,c());return Z}I++;var a={a:Jb};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(a,(d,e)=>{c(b(d,e))})});sa??=ca+"Vosklet.single.wasm";return b((await va(a)).instance)}());
function Kb(){0<I?J=Kb:0<I?J=Kb:(n.calledRun=!0,ha||(pa=!0,Z.R(),ia?.(n)))}Kb();pa?moduleRtn=n:moduleRtn=new Promise((b,a)=>{ia=b;ja=a});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=loadVosklet;module.exports.default=loadVosklet}else if(typeof define==="function"&&define["amd"])define([],()=>loadVosklet);
