var loadVosklet=(()=>{var _scriptName=typeof document!="undefined"?document.currentScript?.src:undefined;return async function(moduleArg={}){var moduleRtn;var n=moduleArg,p="em-ww"==globalThis.name,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope;
if(aa){var q=[];let a=caches.open("Vosklet"),b=[31,139],c=[117,115,116,97,114],d=h=>262<=h.length&&c.every((m,l)=>h[257+l]==m),e=async(h,m)=>{if(d(h))return h;if("undefined"==typeof DecompressionStream){if(1<h.length&&h[0]==b[0]&&h[1]==b[1])throw Error("Model fetch succeeded but gzip decompression is unavailable in this browser (missing DecompressionStream).");throw Error("Fetched model bytes from "+m+" are invalid: expected a USTAR tar archive or gzip-compressed USTAR tar archive.");}try{let l=(new Blob([h])).stream().pipeThrough(new DecompressionStream("gzip")),
x=new Uint8Array(await (new Response(l)).arrayBuffer());if(!d(x))throw Error("decompressed bytes are not a USTAR tar archive");return x}catch(l){throw Error("Unable to decode model as gzip-compressed USTAR tar archive from "+m+": "+(l?.message||l));}},f=URL.createObjectURL(new Blob(["(",(()=>{registerProcessor("VoskletTransferer",class extends AudioWorkletProcessor{constructor(h){super();this.ha=0;this.xa=h.processorOptions[0];this.ua=new Float32Array(this.xa)}process(h){h[0][0]&&(this.ua.set(h[0][0],
this.ha),this.ha+=128,this.ha>=this.xa&&(this.ha=0,this.port.postMessage(this.ua,[this.ua.buffer]),this.ua=new Float32Array(this.xa)));return!0}})}).toString(),")()"],{type:"text/javascript"}));class g extends EventTarget{constructor(){super();q.push(this)}delete(){this.la.delete()}static async ha(h,m,l,x){let u=new g,t=new Promise((D,G)=>{u.addEventListener("status",z=>{z.detail?G(z.detail):(x&&(u.findWord=J=>u.la.findWord(J)),D(u))},{once:!0})}),v=await caches.open("Vosklet");var r=(await v.keys(m,
{ignoreSearch:!0}))[0];if("undefined"==typeof r||r.url.split("?")[1]!=l){r=await fetch(h,{cache:"no-store"});if(!r.ok)throw"Unable to fetch model, status: "+r.status;r=new Response(await e(new Uint8Array(await r.arrayBuffer()),h));await v.put(m+"?"+l,r.clone())}else r=await v.match(r);h=await r.arrayBuffer();m=ca(h.byteLength);(w(),y).set(new Uint8Array(h),m);u.la=new n.CommonModel(q.length-1,x,m,h.byteLength);return t}}class k extends EventTarget{constructor(){super();q.push(this)}delete(){this.la.delete()}static async ha(h,
m,l,x,u){let t=new k,v=new Promise((r,D)=>{t.addEventListener("status",G=>{G.detail?D(G.detail):r(t)},{once:!0})});switch(l){case 1:t.la=new n.Recognizer(q.length-1,m,h);break;case 2:t.la=new n.Recognizer(q.length-1,m,h,u);break;default:t.la=new n.Recognizer(q.length-1,m,h,x,0)}return v}}n={getModelCache:()=>a,cleanUp:async()=>{for(let h of q)await h.delete();URL.revokeObjectURL(f)},createTransferer:async(h,m)=>{await h.audioWorklet.addModule(f);return new AudioWorkletNode(h,"VoskletTransferer",{channelCountMode:"explicit",
numberOfInputs:1,numberOfOutputs:0,channelCount:1,processorOptions:[m]})},createModel:(h,m,l)=>g.ha(h,m,l,!0),createSpkModel:(h,m,l)=>g.ha(h,m,l,!1),createRecognizer:(h,m)=>k.ha(h.la,m,1),createRecognizerWithGrm:(h,m,l)=>k.ha(h.la,m,3,l,null),createRecognizerWithSpkModel:(h,m,l)=>k.ha(h.la,m,2,null,l.la)}}ba&&(_scriptName=self.location.href);var da="",ea,fa;
if(aa||ba){try{da=(new URL(".",_scriptName)).href}catch{}ba&&(fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ha=console.log.bind(console),A=console.error.bind(console),ia=!1;function w(){B.buffer!=C.buffer&&ja()}var ka,la,ma,na;
p&&(onmessage=a=>{onmessage=null;na=a=a.data;B=a.Wa;ja();ma(a.Oa);a.Oa=a.Qa=0});var B,C,y,E,F,H,I,oa,pa,qa,ra,sa=!1;function ja(){var a=B.buffer;C=new Int8Array(a);E=new Int16Array(a);y=new Uint8Array(a);F=new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);oa=new Float32Array(a);pa=new Float64Array(a);qa=new BigInt64Array(a);ra=new BigUint64Array(a)}function ta(){sa=!0;p?(ua(na.Ta,na.Ua),va(),removeEventListener("message",wa),xa=xa.forEach(ya),addEventListener("message",ya)):K.T()}
var L=0,M=null;function za(a){a="Aborted("+a+")";A(a);ia=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");la?.(a);throw a;}var Aa;async function Ca(a){try{var b=await ea(a);return new Uint8Array(b)}catch{}if(fa)a=fa(a);else throw"both async and sync fetching of the wasm failed";return a}async function Da(a,b){try{var c=await Ca(a);return await WebAssembly.instantiate(c,b)}catch(d){A(`failed to asynchronously prepare wasm: ${d}`),za(d)}}
async function Ea(a){var b=Aa;try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){A(`wasm streaming compile failed: ${d}`),A("falling back to ArrayBuffer instantiation")}return Da(b,a)}function Fa(){Ga={b:Ha,c:Ia,J:Ja,q:Ka,N:La,o:Ma,i:Na,f:Oa,L:Pa,K:Qa,j:Ra,p:Sa,S:Ta,g:Ua,d:Va,M:Wa,m:Xa,O:Ya,s:Za,t:$a,F:ab,A:bb,y:cb,z:db,w:eb,u:fb,B:gb,x:hb,v:ib,D:jb,h:kb,P:lb,R:mb,Q:ob,e:pb,k:qb,l:rb,C:sb,G:tb,H:ub,I:vb,n:wb,a:B,r:xb,E:yb};return{a:Ga}}
class zb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var xa=[],xb=a=>{throw new zb(a);},wb=a=>{throw new zb(a);},Ab=a=>{if(!ia)try{a()}catch(b){if(!(b instanceof zb||"unwind"==b))throw b;}},Bb=[],Cb,Db=a=>{var b=Bb[a];b||(Bb[a]=b=Cb.get(a));return b},ya=a=>{let b=a.data,c=b._wsc;c&&Ab(()=>Db(c)(...b.x))},wa=a=>{xa.push(a)},Eb=new TextDecoder,Fb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},N=(a,b,c)=>{if(!a)return"";b=Fb((w(),y),a,b,c);return Eb.decode((w(),y).slice(a,b))},Ha=(a,b,c,d)=>za(`Assertion failed: ${N(a)}, at: `+[b?N(b):
"unknown filename",c,d?N(d):"unknown function"]);class Gb{constructor(a){this.ba=a-24}}var Hb=0,Ib=0,Ia=(a,b,c)=>{var d=new Gb(a);(w(),I)[d.ba+16>>2]=0;(w(),I)[d.ba+4>>2]=b;(w(),I)[d.ba+8>>2]=c;Hb=a;Ib++;throw Hb;},Ja=()=>za(""),O=a=>{for(var b="";;){var c=(w(),y)[a++];if(!c)return b;b+=String.fromCharCode(c)}},P={},Q={},Jb={},R=class extends Error{constructor(a){super(a);this.name="BindingError"}},Kb=a=>{throw new R(a);};
function Lb(a,b,c={}){var d=b.name;if(!a)throw new R(`type "${d}" must have a positive integer typeid pointer`);if(Q.hasOwnProperty(a)){if(c.Ha)return;throw new R(`Cannot register type '${d}' twice`);}Q[a]=b;delete Jb[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(e=>e()))}function S(a,b,c={}){return Lb(a,b,c)}
var Mb=(a,b,c)=>{switch(b){case 1:return c?d=>(w(),C)[d]:d=>(w(),y)[d];case 2:return c?d=>(w(),E)[d>>1]:d=>(w(),F)[d>>1];case 4:return c?d=>(w(),H)[d>>2]:d=>(w(),I)[d>>2];case 8:return c?d=>(w(),qa)[d>>3]:d=>(w(),ra)[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ka=(a,b,c,d,e)=>{b=O(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}S(a,{name:b,ca:f,ka:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},ma:Mb(b,c,!d),ia:null})},La=(a,b,c,d)=>{b=O(b);
S(a,{name:b,ca:function(e){return!!e},ka:function(e,f){return f?c:d},ma:function(e){return this.ca((w(),y)[e])},ia:null})},Nb=a=>{throw new R(a.$.da.aa.name+" instance already deleted");},Ob=!1,Pb=()=>{},T=a=>{if("undefined"===typeof FinalizationRegistry)return T=b=>b,a;Ob=new FinalizationRegistry(b=>{b=b.$;--b.count.value;0===b.count.value&&(b.fa?b.ja.na(b.fa):b.da.aa.na(b.ba))});T=b=>{var c=b.$;c.fa&&Ob.register(b,{$:c},b);return b};Pb=b=>{Ob.unregister(b)};return T(a)},Qb=[];function Rb(){}
var Sb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Tb={},Ub=(a,b,c)=>{if(void 0===a[b].ea){var d=a[b];a[b]=function(...e){if(!a[b].ea.hasOwnProperty(e.length))throw new R(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ea})!`);return a[b].ea[e.length].apply(this,e)};a[b].ea=[];a[b].ea[d.qa]=d}},Vb=(a,b,c)=>{if(n.hasOwnProperty(a)){if(void 0===c||void 0!==n[a].ea&&void 0!==n[a].ea[c])throw new R(`Cannot register public name '${a}' twice`);Ub(n,
a,a);if(n[a].ea.hasOwnProperty(c))throw new R(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);n[a].ea[c]=b}else n[a]=b,n[a].qa=c},Wb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Xb(a,b,c,d,e,f,g,k){this.name=a;this.constructor=b;this.pa=c;this.na=d;this.ga=e;this.Fa=f;this.ta=g;this.Da=k;this.Ka=[]}
var Yb=(a,b,c)=>{for(;b!==c;){if(!b.ta)throw new R(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ta(a);b=b.ga}return a},Zb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function $b(a,b){if(null===b){if(this.ya)throw new R(`null is not a valid ${this.name}`);return 0}if(!b.$)throw new R(`Cannot pass "${Zb(b)}" as a ${this.name}`);if(!b.$.ba)throw new R(`Cannot pass deleted object as a pointer of type ${this.name}`);return Yb(b.$.ba,b.$.da.aa,this.aa)}
function ac(a,b){if(null===b){if(this.ya)throw new R(`null is not a valid ${this.name}`);if(this.wa){var c=this.La();null!==a&&a.push(this.na,c);return c}return 0}if(!b||!b.$)throw new R(`Cannot pass "${Zb(b)}" as a ${this.name}`);if(!b.$.ba)throw new R(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.va&&b.$.da.va)throw new R(`Cannot convert argument of type ${b.$.ja?b.$.ja.name:b.$.da.name} to parameter type ${this.name}`);c=Yb(b.$.ba,b.$.da.aa,this.aa);if(this.wa){if(void 0===
b.$.fa)throw new R("Passing raw pointer to smart pointer is illegal");switch(this.Na){case 0:if(b.$.ja===this)c=b.$.fa;else throw new R(`Cannot convert argument of type ${b.$.ja?b.$.ja.name:b.$.da.name} to parameter type ${this.name}`);break;case 1:c=b.$.fa;break;case 2:if(b.$.ja===this)c=b.$.fa;else{var d=b.clone();c=this.Ma(c,bc(()=>d["delete"]()));null!==a&&a.push(this.na,c)}break;default:throw new R("Unsupporting sharing policy");}}return c}
function cc(a,b){if(null===b){if(this.ya)throw new R(`null is not a valid ${this.name}`);return 0}if(!b.$)throw new R(`Cannot pass "${Zb(b)}" as a ${this.name}`);if(!b.$.ba)throw new R(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.$.da.va)throw new R(`Cannot convert argument of type ${b.$.da.name} to parameter type ${this.name}`);return Yb(b.$.ba,b.$.da.aa,this.aa)}function dc(a){return this.ca((w(),I)[a>>2])}
var ec=(a,b,c)=>{if(b===c)return a;if(void 0===c.ga)return null;a=ec(a,b,c.ga);return null===a?null:c.Da(a)},fc={},gc=(a,b)=>{if(void 0===b)throw new R("ptr should not be undefined");for(;a.ga;)b=a.ta(b),a=a.ga;return fc[b]},hc=class extends Error{constructor(a){super(a);this.name="InternalError"}},ic=(a,b)=>{if(!b.da||!b.ba)throw new hc("makeClassHandle requires ptr and ptrType");if(!!b.ja!==!!b.fa)throw new hc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return T(Object.create(a,
{$:{value:b,writable:!0}}))};function jc(a,b,c,d,e,f,g,k,h,m,l){this.name=a;this.aa=b;this.ya=c;this.va=d;this.wa=e;this.Ja=f;this.Na=g;this.Ba=k;this.La=h;this.Ma=m;this.na=l;e||void 0!==b.ga?this.ka=ac:(this.ka=d?$b:cc,this.ia=null)}
var kc=(a,b,c)=>{if(!n.hasOwnProperty(a))throw new hc("Replacing nonexistent public symbol");void 0!==n[a].ea&&void 0!==c?n[a].ea[c]=b:(n[a]=b,n[a].qa=c)},U=(a,b)=>{a=O(a);var c=Db(b);if("function"!=typeof c)throw new R(`unknown function pointer with signature ${a}: ${b}`);return c};class lc extends Error{}
var nc=a=>{a=mc(a);var b=O(a);V(a);return b},oc=(a,b)=>{function c(f){e[f]||Q[f]||(Jb[f]?Jb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new lc(`${a}: `+d.map(nc).join([", "]));},W=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new hc("Mismatched type converter count");for(var h=0;h<a.length;++h)S(a[h],k[h])}a.forEach(k=>Jb[k]=b);var e=Array(b.length),f=[],g=0;b.forEach((k,h)=>{Q.hasOwnProperty(k)?e[h]=Q[k]:(f.push(k),P.hasOwnProperty(k)||(P[k]=[]),P[k].push(()=>
{e[h]=Q[k];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Ma=(a,b,c,d,e,f,g,k,h,m,l,x,u)=>{l=O(l);f=U(e,f);k&&=U(g,k);m&&=U(h,m);u=U(x,u);var t=Wb(l);Vb(t,function(){oc(`Cannot construct ${l} due to unbound types`,[d])});W([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var r=v.aa;var D=r.pa}else D=Rb.prototype;v=Sb(l,function(...Ba){if(Object.getPrototypeOf(this)!==G)throw new R(`Use 'new' to construct ${l}`);if(void 0===z.oa)throw new R(`${l} has no accessible constructor`);var nb=z.oa[Ba.length];if(void 0===
nb)throw new R(`Tried to invoke ctor of ${l} with invalid number of parameters (${Ba.length}) - expected (${Object.keys(z.oa).toString()}) parameters instead!`);return nb.apply(this,Ba)});var G=Object.create(D,{constructor:{value:v}});v.prototype=G;var z=new Xb(l,v,G,u,r,f,k,m);if(z.ga){var J;(J=z.ga).za??(J.za=[]);z.ga.za.push(z)}r=new jc(l,z,!0,!1,!1);J=new jc(l+"*",z,!1,!1,!1);D=new jc(l+" const*",z,!1,!0,!1);Tb[a]={pointerType:J,Ca:D};kc(t,v);return[r,J,D]})},pc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push((w(),
I)[b+4*d>>2]);return c},qc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function rc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ia)return!0;return!1}
function sc(a,b,c,d,e,f){var g=b.length;if(2>g)throw new R("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,h=rc(b);c=!b[0].Ia;var m=b[0],l=b[1];d=[a,Kb,d,e,qc,m.ca.bind(m),l?.ka.bind(l)];for(e=2;e<g;++e)m=b[e],d.push(m.ka.bind(m));if(!h)for(e=k?1:2;e<b.length;++e)null!==b[e].ia&&d.push(b[e].ia);h=rc(b);e=b.length-2;l=[];m=["fn"];k&&m.push("thisWired");for(g=0;g<e;++g)l.push(`arg${g}`),m.push(`arg${g}Wired`);l=l.join(",");m=m.join(",");
l=`return function (${l}) {\n`;h&&(l+="var destructors = [];\n");var x=h?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(l+=`var thisWired = toClassParamWire(${x}, this);\n`);for(g=0;g<e;++g){var t=`toArg${g}Wire`;l+=`var arg${g}Wired = ${t}(${x}, arg${g});\n`;u.push(t)}l+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(h)l+="runDestructors(destructors);\n";else for(g=k?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].ia&&(l+=`${f}_dtor(${f});\n`,u.push(`${f}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(u,l+"}\n"))(...d);return Sb(a,b)}
var Na=(a,b,c,d,e,f)=>{var g=pc(b,c);e=U(d,e);W([],[a],k=>{k=k[0];var h=`constructor ${k.name}`;void 0===k.aa.oa&&(k.aa.oa=[]);if(void 0!==k.aa.oa[b-1])throw new R(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.aa.oa[b-1]=()=>{oc(`Cannot construct ${k.name} due to unbound types`,g)};W([],g,m=>{m.splice(1,0,null);k.aa.oa[b-1]=sc(h,m,null,e,
f);return[]});return[]})},tc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Oa=(a,b,c,d,e,f,g,k,h)=>{var m=pc(c,d);b=O(b);b=tc(b);f=U(e,f);W([],[a],l=>{function x(){oc(`Cannot call ${u} due to unbound types`,m)}l=l[0];var u=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&l.aa.Ka.push(b);var t=l.aa.pa,v=t[b];void 0===v||void 0===v.ea&&v.className!==l.name&&v.qa===c-2?(x.qa=c-2,x.className=l.name,t[b]=x):(Ub(t,b,u),t[b].ea[c-2]=x);W([],m,r=>{r=sc(u,r,l,f,g,h);
void 0===t[b].ea?(r.qa=c-2,t[b]=r):t[b].ea[c-2]=r;return[]});return[]})},uc=[],X=[0,1,,1,null,1,!0,1,!1,1],bc=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=uc.pop()||X.length;X[b]=a;X[b+1]=1;return b}},vc={name:"emscripten::val",ca:a=>{if(!a)throw new R(`Cannot use deleted val. handle = ${a}`);var b=X[a];9<a&&0===--X[a+1]&&(X[a]=void 0,uc.push(a));return b},ka:(a,b)=>bc(b),ma:dc,ia:null},Pa=a=>S(a,vc),wc=(a,b,c)=>{switch(b){case 1:return c?
function(d){return this.ca((w(),C)[d])}:function(d){return this.ca((w(),y)[d])};case 2:return c?function(d){return this.ca((w(),E)[d>>1])}:function(d){return this.ca((w(),F)[d>>1])};case 4:return c?function(d){return this.ca((w(),H)[d>>2])}:function(d){return this.ca((w(),I)[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Qa=(a,b,c,d)=>{function e(){}b=O(b);e.values={};S(a,{name:b,constructor:e,ca:function(f){return this.constructor.values[f]},ka:(f,g)=>g.value,ma:wc(b,
c,d),ia:null});Vb(b,e)},xc=a=>{var b=Q[a];if(void 0===b)throw a=`${"enum"} has unknown type ${nc(a)}`,new R(a);return b},Ra=(a,b,c)=>{var d=xc(a);b=O(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Sb(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},yc=(a,b)=>{switch(b){case 4:return function(c){return this.ca((w(),oa)[c>>2])};case 8:return function(c){return this.ca((w(),pa)[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);
}},Sa=(a,b,c)=>{b=O(b);S(a,{name:b,ca:d=>d,ka:(d,e)=>e,ma:yc(b,c),ia:null})},Ta=(a,b,c,d,e,f,g)=>{var k=pc(b,c);a=O(a);a=tc(a);e=U(d,e);Vb(a,function(){oc(`Cannot call ${a} due to unbound types`,k)},b-1);W([],k,h=>{kc(a,sc(a,[h[0],null].concat(h.slice(1)),null,e,f,g),b-1);return[]})},Ua=(a,b,c,d,e)=>{b=O(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}S(a,{name:b,ca:f,ka:(k,h)=>h,ma:Mb(b,c,0!==d),ia:null})},Va=(a,b,c)=>{function d(f){var g=(w(),I)[f>>2];f=(w(),I)[f+4>>2];return new e((w(),
C).buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=O(c);S(a,{name:c,ca:d,ma:d},{Ha:!0})},zc=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=
240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Y=(a,b,c)=>zc(a,(w(),y),b,c),Z=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Wa=(a,b)=>{b=O(b);S(a,{name:b,ca(c){var d=(w(),I)[c>>2];d=N(c+4,d,!0);V(c);return d},ka(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new R("Cannot pass non-string to std::string");
var f=e?Z(d):d.length;var g=ca(4+f+1),k=g+4;(w(),I)[g>>2]=f;e?Y(d,k,f+1):(w(),y).set(d,k);null!==c&&c.push(V,g);return g},ma:dc,ia(c){V(c)}})},Ac=new TextDecoder("utf-16le"),Bc=(a,b,c)=>{a>>=1;b=Fb((w(),F),a,b/2,c);return Ac.decode((w(),F).buffer instanceof ArrayBuffer?(w(),F).subarray(a,b):(w(),F).slice(a,b))},Cc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);(w(),E)[b>>1]=f;b+=2}(w(),E)[b>>1]=0;return b-d},Dc=a=>2*a.length,
Ec=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=(w(),I)[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Fc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;(w(),H)[b>>2]=f;b+=4;if(b+4>c)break}(w(),H)[b>>2]=0;return b-d},Gc=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Xa=(a,b,c)=>{c=O(c);if(2===b){var d=Bc;var e=Cc;var f=Dc}else d=Ec,e=Fc,f=Gc;S(a,{name:c,ca:g=>{var k=(w(),
I)[g>>2];k=d(g+4,k*b,!0);V(g);return k},ka:(g,k)=>{if("string"!=typeof k)throw new R(`Cannot pass non-string to C++ string type ${c}`);var h=f(k),m=ca(4+h+b);(w(),I)[m>>2]=h/b;e(k,m+4,h+b);null!==g&&g.push(V,m);return m},ma:dc,ia(g){V(g)}})},Ya=(a,b)=>{b=O(b);S(a,{Ia:!0,name:b,ca:()=>{},ka:()=>{}})},Za=()=>{},Hc={},rb=()=>performance.now(),$a=(a,b)=>{Hc[a]&&(clearTimeout(Hc[a].id),delete Hc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Hc[a];Ab(()=>Ic(a,performance.now()))},b);Hc[a]={id:c,Va:b};
return 0},ab=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(w(),I)[a>>2]=60*g;(w(),H)[b>>2]=Number(f!=e);b=k=>{var h=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Y(a,c,17),Y(b,d,17)):(Y(a,d,17),Y(b,c,17))},bb=(a,b)=>(w(),y).set(Jc[a].Ea,b),Kc=[],cb=()=>Kc.length,Jc=[],db=()=>Jc.length,eb=(a,b)=>{a=Kc[a].Pa;Y(a,b,Z(a)+
1)},fb=a=>Jc[a].mode,gb=a=>Jc[a].Ea.length,hb=(a,b)=>{a=Kc[a].Ra;Y(a,b,Z(a)+1)},ib=(a,b)=>{a=Jc[a].Sa;Y(a,b,Z(a)+1)},Lc=[],jb=()=>{a:{if(!Lc.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Z(a)+1);a=zc(a,b,0,b.length);b.length=a;Lc=b}b=Lc.shift()}return"number"===typeof b?b:-1},lb=a=>{console.error(N(a))},mb=a=>{console.log(N(a))},ob=a=>{console.warn(N(a))},pb=()=>Date.now(),qb=a=>A(N(a)),
sb=a=>ha(N(a)),tb=a=>{var b=(w(),y).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(d);ja();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Mc={},Oc=()=>{if(!Nc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+
".UTF-8",_:"./this.program"},b;for(b in Mc)void 0===Mc[b]?delete a[b]:a[b]=Mc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Nc=c}return Nc},Nc,ub=(a,b)=>{var c=0,d=0,e;for(e of Oc()){var f=b+c;(w(),I)[a+d>>2]=f;c+=Y(e,f,Infinity)+1;d+=4}return 0},vb=(a,b)=>{var c=Oc();(w(),I)[a>>2]=c.length;a=0;for(var d of c)a+=Z(d)+1;(w(),I)[b>>2]=a;return 0},Pc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),Qc=a=>{(Qc=Pc())(a)},yb=(a,b)=>{Qc((w(),y).subarray(a,a+b));return 0};
(()=>{let a=Rb.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Rb&&c instanceof Rb))return!1;var d=this.$.da.aa,e=this.$.ba;c.$=c.$;var f=c.$.da.aa;for(c=c.$.ba;d.ga;)e=d.ta(e),d=d.ga;for(;f.ga;)c=f.ta(c),f=f.ga;return d===f&&e===c},clone:function(){this.$.ba||Nb(this);if(this.$.sa)return this.$.count.value+=1,this;var c=T,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.$;c=c(e.call(d,f,{$:{value:{count:g.count,ra:g.ra,sa:g.sa,ba:g.ba,da:g.da,fa:g.fa,ja:g.ja}}}));c.$.count.value+=
1;c.$.ra=!1;return c},["delete"](){this.$.ba||Nb(this);if(this.$.ra&&!this.$.sa)throw new R("Object already scheduled for deletion");Pb(this);var c=this.$;--c.count.value;0===c.count.value&&(c.fa?c.ja.na(c.fa):c.da.aa.na(c.ba));this.$.sa||(this.$.fa=void 0,this.$.ba=void 0)},isDeleted:function(){return!this.$.ba},deleteLater:function(){this.$.ba||Nb(this);if(this.$.ra&&!this.$.sa)throw new R("Object already scheduled for deletion");Qb.push(this);this.$.ra=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(jc.prototype,{Ga(a){this.Ba&&(a=this.Ba(a));return a},Aa(a){this.na?.(a)},ma:dc,ca:function(a){function b(){return this.wa?ic(this.aa.pa,{da:this.Ja,ba:c,ja:this,fa:a}):ic(this.aa.pa,{da:this,ba:a})}var c=this.Ga(a);if(!c)return this.Aa(a),null;var d=gc(this.aa,c);if(void 0!==d){if(0===d.$.count.value)return d.$.ba=c,d.$.fa=a,d.clone();d=d.clone();this.Aa(a);return d}d=this.aa.Fa(c);d=Tb[d];if(!d)return b.call(this);d=this.va?d.Ca:d.pointerType;var e=ec(c,this.aa,d.aa);return null===
e?b.call(this):this.wa?ic(d.aa.pa,{da:d,ba:e,ja:this,fa:a}):ic(d.aa.pa,{da:d,ba:e})}});p||(n.wasmMemory?B=n.wasmMemory:B=new WebAssembly.Memory({initial:5040,maximum:32768,shared:!0}),ja());function kb(a,b){q[a].dispatchEvent(new CustomEvent("status",{detail:0===b?null:N(b)}))}
var V,ca,mc,va,Ic,ua,Ga,K=await (async function(){function a(c){K=c.exports;Cb=K.Y;c=K;V=c.U;ca=c.V;mc=c.W;va=c.X;Ic=c.Z;ua=c._;L--;0==L&&M&&(c=M,M=null,c());return K}L++;var b=Fa();if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(b,(d,e)=>{c(a(d,e))})});if(p)return new Promise(c=>{ma=d=>{var e=new WebAssembly.Instance(d,Fa());c(a(e,d))}});Aa??=n.locateFile?n.locateFile("Vosklet.wasm",da):da+"Vosklet.wasm";return function(c){return a(c.instance,c.module)}(await Ea(b))}());
function Rc(){0<L?M=Rc:p?(ka?.(n),ta()):0<L?M=Rc:(n.calledRun=!0,ia||(ta(),ka?.(n)))}Rc();sa?moduleRtn=n:moduleRtn=new Promise((a,b)=>{ka=a;la=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=loadVosklet;module.exports.default=loadVosklet}else if(typeof define==="function"&&define["amd"])define([],()=>loadVosklet);var isWW=globalThis.self?.name=="em-ww";isWW&&loadVosklet();
